# Generated by Django 4.0.3 on 2022-03-10 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vaccines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dose',
            name='vaccine_records',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dose', to='vaccines.vaccinerecord'),
        ),
    ]
