# Generated by Django 4.0.3 on 2022-03-11 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('image', models.ImageField(blank=True, null=True, upload_to='people')),
                ('national_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('home_address', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=100)),
                ('vaccinate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'people',
            },
        ),
        migrations.CreateModel(
            name='StakeHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('representative_name', models.CharField(max_length=50)),
                ('representative_id', models.CharField(max_length=50)),
                ('contacts', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('username', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'stakeholders',
            },
        ),
    ]
