# Generated by Django 4.0.3 on 2022-03-09 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('national_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('home_address', models.CharField(max_length=200)),
                ('email_address', models.EmailField(max_length=50)),
                ('phone_number', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'people',
            },
        ),
    ]
