# Generated by Django 4.0.3 on 2022-03-10 03:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_person_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='vaccinate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='people'),
        ),
        migrations.CreateModel(
            name='StakeHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation', models.CharField(max_length=100)),
                ('contacts', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('representative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.person')),
            ],
            options={
                'db_table': 'stakeholders',
            },
        ),
    ]
