# Generated by Django 4.0.3 on 2022-03-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_person_vaccinate_alter_person_image_stakeholder'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='nationality',
            field=models.CharField(default='Zimbabwean', max_length=100),
            preserve_default=False,
        ),
    ]
