# Generated by Django 4.0.3 on 2022-03-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_person_nationality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stakeholder',
            name='representative',
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='representative_id',
            field=models.CharField(default=-1.23413e+50, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='representative_name',
            field=models.CharField(default='Gorolio', max_length=50),
            preserve_default=False,
        ),
    ]
