# Generated by Django 4.0.3 on 2022-03-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_stakeholder_representative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='branch',
            field=models.CharField(default='J-Moyo', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='username',
            field=models.CharField(default='Users', max_length=50),
            preserve_default=False,
        ),
    ]
